#! /bin/bash

CONTINUAR=1

while [ $CONTINUAR -eq 1 ]
do
#contador de ips validos
contv=0 
#contador de dados invalidos
conti=0
ativos=0
inativos=0
invalidos=0
hora=$(date +%H)
ipvalido="^([0-9]|[1-8][0-9]|9[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-8][0-9]|9[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])){3}$"
ipativo="(\b([0-9]{2}|[0-9]{1}|[^100])% packet loss)"
ipinativo="(100% packet loss)"
clear

## cumprimento com o usuario, opcional e apenas uma frescura que eu inventei - carvalho

if [ 6 -lt $hora ] && [ $hora -lt 12 ] ; then
    echo -en "\033[32mBom dia, $USER. Aceita um cafe? \033[0m"
	echo 
else if [ 12 -lt $hora ] && [ $hora -lt 18 ] ; then
    echo -en "\033[32mBoa tarde, $USER. Aceita um suco? \033[0m"
	echo 
else if [ 18 -lt $hora ] && [ $hora -lt 23 ] ; then
    echo -en "\033[32m Boa noite, $USER. Hora da breja.\033[0m"
	echo 
fi ; fi ; fi

if [ $# -eq 0 ] || [ ! -f $1 ]; then 
## se nenhum parametro foi passado
	echo -en "\033[31mNenhum caminho foi informado. \033[0m"
    echo
	input=0
	while [ ! -f $input ]
	do
	## enquanto input nao for um arquivo valido
		echo  -en "\033[32mInsira o caminho do arquivo. \033[0m"
        echo
		echo  -en "\033[32mobs:caso esteja no diretorio, por favor informar somente o nome do arquivo. \033[0m" 
        echo
		read input
		if [ ! -f $input ] ; then
			clear
			echo -en "\033[31mCaminho invalido. \033[0m"
            echo
		fi
	done
else if [ -f $1 ] ; then
## se foi, input = parametro
		input=$1
	fi
fi

echo > valido.txt ; #echo VALIDOS > valido.txt ## criaçao de arquivos, talvez tentar juntar em apenas um? - carvalho
echo > invalido.txt ; #echo INVALIDOS > invalido.txt

while IFS= read -r line
do
	if [[ $line =~ $ipvalido ]] ; then
		if [ $contv -eq 0 ] ; then
            echo -en "\033[01mTestando os enderecos... aguarde.\033[0m"
            echo
            echo -en "\033[33m[\033[0m"
			echo -n "$line - " > valido.txt
		else 
			echo -n "$line - " >> valido.txt
		fi
		ping -c 4 $line | egrep -wo "([0-9]?[0-9]?[0-9]% packet loss)" >> valido.txt
		(( contv++ ))
		echo -en "*"
        else 
		if [ $conti -eq 0 ] ; then 
		echo "$line" > invalido.txt
		fi
		echo "$line" >> invalido.txt
		(( conti++ ))
	fi
done < "$input"
echo -en "\033[33m]\033[0m"

##daqui pra baixo ainda eh trabalho em progresso. juntar os validos e invalidos no resultado.txt - carvalho
## aparentemente tem um bug em que alguns endereços sao repetidos e imprimidos duas vezes. importante checar - carvalho

valido=valido.txt
invalido=invalido.txt

echo ' ' 
echo -en "\033[04m---------------------------------------------\033[0m"
echo ' '
echo -e "\tENDERECOS ATIVOS" > resultado.txt

while IFS= read -r line
do
	if [[ $line =~ $ipativo ]] ; then 
		echo -en "\t" >> resultado.txt && echo $line >> resultado.txt
		(( ativos++ ))
	fi
done < "$valido"
echo -e "\tTOTAL:" "$ativos" "ENDERECOS ATIVOS" >> resultado.txt
echo >> resultado.txt

echo -e "\tENDERECOS INATIVOS" >> resultado.txt 
while IFS= read -r line
do
	if [[ $line =~ $ipinativo ]] ; then 
		echo -en "\t" >> resultado.txt && echo $line >> resultado.txt
		(( inativos++ ))
	fi
done < "$valido"
echo -e "\tTOTAL:" "$inativos" "ENDERECOS INATIVOS" >> resultado.txt
echo >> resultado.txt

echo -e "\tENDERECOS INVALIDOS" >> resultado.txt 
while IFS= read -r line
do
	echo -en "\t" >> resultado.txt && echo $line >> resultado.txt
	(( invalidos ++ ))
done < "$invalido"
echo -e "\tTOTAL:" "$invalidos" "ENDERECOS INVALIDOS" >> resultado.txt

cat resultado.txt

#echo
#echo -en "\033[32mFim de arquivo\033[0m"
echo 
echo -en "\033[32mDeseja exportar os resultados para um arquivo? [s/n]\033[0m"
echo 
read op 
	case $op in 
	"s" | "S")
	echo -en "\033[32mInsira o nome do arquivo a ser exportado.\033[0m"
	echo 
	read nome 
	cat resultado.txt > $nome.txt
	esac
echo
echo -en "\033[32mDeseja inserir um novo arquivo? [s/n]\033[0m"
echo 
read resp
	case $resp in
	"s" | "S")
	echo > valido.txt  && echo > invalido.txt && echo > resultado.txt
	CONTINUAR=1
	;;
	"n" | "N")
	CONTINUAR=0
	;;
	*)
	CONTINUAR=0
	;;
esac
sleep 1
clear   
done

#aqui esta dando pau, era para pegar letras diferente de s e n;
#if [ "$resp" -ne "s" ] ; then
#     while true
#     do
#       echo "digite novamente"
#       read t
#       if [ "$t" = "s" ] ; then
#       break
#       fi
#     done
#fi  